// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizasyonSitesi.Data;

#nullable disable

namespace OrganizasyonSitesi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709184256_SeedDataEklendi")]
    partial class SeedDataEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrganizasyonSitesi.Models.Entities.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hizmetler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Lansman, bayi toplantısı, gala gecesi ve şirket organizasyonlarında uçtan uca planlama.",
                            AktifMi = true,
                            Baslik = "Kurumsal Etkinlikler",
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Nişandan kına gecesine, salon süslemesinden orkestraya hayalinizdeki düğünü kurgular, siz sadece anın tadını çıkarırsınız.",
                            AktifMi = true,
                            Baslik = "Düğün Organizasyonu",
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Sahne kurulumu, ses-ışık sistemleri, sanatçı yönetimi ve güvenlik koordinasyonu dahil büyük ölçekli etkinlik yönetimi.",
                            AktifMi = true,
                            Baslik = "Festival ve Konser",
                            SiraNo = 3
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Mağaza açılışı, ürün lansmanı ve basın etkinliklerinde markanızı en doğru şekilde sahneye koyuyoruz.",
                            AktifMi = true,
                            Baslik = "Açılış ve Lansman",
                            SiraNo = 4
                        });
                });

            modelBuilder.Entity("OrganizasyonSitesi.Models.Entities.IletisimMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EtkinlikTuru")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("OrganizasyonSitesi.Models.Entities.Referans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Yorum")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Referanslar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            MusteriAdi = "Yılmaz Holding",
                            Yorum = "Bayi toplantımız kusursuz geçti, her detay düşünülmüştü."
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            MusteriAdi = "Elif & Mert",
                            Yorum = "Düğünümüz hayal ettiğimizden de güzeldi, iyi ki sizi seçmişiz!"
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = true,
                            MusteriAdi = "TechNova Yazılım",
                            Yorum = "Ürün lansmanımızda basın ve konuk yönetimi profesyonelceydi."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
